- name: AWX test
  hosts: all
  become: yes 

  tasks:

  - name: Create User
    user:
      name: "{{new_user}}"
      home: "/home/{{new_user}}"
      shell: /bin/bash
      groups: www-data
      append: yes
      password: "{{user_pw}}"

  - name: Create Folder
    file:
      path: "/var/www/{{new_user}}"
      state: directory
      recurese: yes
      owner: "{{new_user}}"
      group: "{{new_user}}"
      mode: 0755 