- name: AWX test
  hosts: all
  become: yes 

  tasks:

  - name: Create User
    user:
      name: "mellivoora"
      home: "/home/mellivoora"
      shell: /bin/bash
      groups: www-data
      append: yes
      password: "user_pw"
      
      
